Dev Diary June 2017
cmontella/blog pull request #5
Opened 2017-07-06 19:31 UTC by cmontella

2017-07-07 21:51 UTC, joshuafcole commented on _posts/2017-07-06-June.md
> +We released a new preview of v0.3, that includes several bug fixes and some new features. For a full changelog, see the [release notes](http://incidentalcomplexity.com/2017/06/28/release-0.3p5/). Two
"open Eve up to using Eve in new ways"

2017-07-07 21:51 UTC, joshuafcole commented on _posts/2017-07-06-June.md
> +We've supported running Eve in headless mode (without hooks to the browser) for a while now, but it wasn't useful since most of our UI, debugging, and IO at the moment are done through the browser. T
"sdtout" -> "stdout"

2017-07-07 21:52 UTC, joshuafcole commented on _posts/2017-07-06-June.md
> +Speaking of getting data into Eve, the `file` library allows you write and read files directly from the filesystem, opening up the ability to read larger datasets into Eve. We'll be shortly adding fa
"JSON and CSS" -> "JSON and CSV"

2017-07-07 21:53 UTC, joshuafcole commented on _posts/2017-07-06-June.md
> +Speaking of getting data into Eve, the `file` library allows you write and read files directly from the filesystem, opening up the ability to read larger datasets into Eve. We'll be shortly adding fa
Drop "for starters"

2017-07-07 21:56 UTC, joshuafcole commented on _posts/2017-07-06-June.md
> +Brian Theado has been working on [Tweve](https://btheado.github.io/tweve/), which marries Eve and Tiddlywiki. Tiddlywiki is a notebook-like environment that allows you to embed rich-content in your n
"multiple programs in a single document" AND ALSO "multiple documents as a single program"

2017-07-07 21:58 UTC, joshuafcole commented on _posts/2017-07-06-June.md
> +Brian Theado has been working on [Tweve](https://btheado.github.io/tweve/), which marries Eve and Tiddlywiki. Tiddlywiki is a notebook-like environment that allows you to embed rich-content in your n
The last sentence feels off-putting. Maybe instead encourage users interested in tiddlywiki to give it a shot or contribute to it's development?

2017-07-07 22:05 UTC, ibdthor requested changes

2017-07-07 22:05 UTC, ibdthor commented on _posts/2017-07-06-June.md
> +We released a new preview of v0.3, that includes several bug fixes and some new features. For a full changelog, see the [release notes](http://incidentalcomplexity.com/2017/06/28/release-0.3p5/). Two
no comma after "v0.3"

2017-07-07 22:05 UTC, ibdthor commented on _posts/2017-07-06-June.md
> +We released a new preview of v0.3, that includes several bug fixes and some new features. For a full changelog, see the [release notes](http://incidentalcomplexity.com/2017/06/28/release-0.3p5/). Two
"please see the release notes"

2017-07-07 22:05 UTC, ibdthor commented on _posts/2017-07-06-June.md
> +We've supported running Eve in headless mode (without hooks to the browser) for a while now, but it wasn't useful since most of our UI, debugging, and IO at the moment are done through the browser. T
"awhile", one word

2017-07-07 22:05 UTC, ibdthor commented on _posts/2017-07-06-June.md
> +Speaking of getting data into Eve, the `file` library allows you write and read files directly from the filesystem, opening up the ability to read larger datasets into Eve. We'll be shortly adding fa
"adding facilities shortly", more typical adverb syntax

2017-07-07 22:05 UTC, ibdthor commented on _posts/2017-07-06-June.md
> +Many of you have asked about the status of v0.4, and we're pleased to say it's coming along nicely. For those who don't know, the v0.4 runtime is implemented in Rust, mainly for increased performance
"research of Frank McSherry in"

2017-07-07 22:05 UTC, ibdthor commented on _posts/2017-07-06-June.md
> +We opened a [community slack channel](https://slack-signup.witheve.com/), so you can chat with and get help from us and fellow Eve developers. There's usually at least one dev hanging around the chan
"For now we're keeping it casual, so drop by..."

2017-07-07 22:05 UTC, ibdthor commented on _posts/2017-07-06-June.md
> +Brian Theado has been working on [Tweve](https://btheado.github.io/tweve/), which marries Eve and Tiddlywiki. Tiddlywiki is a notebook-like environment that allows you to embed rich-content in your n
is "rich-content" supposed to be hyphenated?

2017-07-07 22:05 UTC, ibdthor commented on _posts/2017-07-06-June.md
> +**San Francisco June 27**
"San Francisco, June 27"

2017-07-07 23:07 UTC, ibdknox commented on _posts/2017-07-06-June.md
> +Brian Theado has been working on [Tweve](https://btheado.github.io/tweve/), which marries Eve and Tiddlywiki. Tiddlywiki is a notebook-like environment that allows you to embed rich-content in your n
remove:
> (a feature that we demoed internally but never released)

2017-07-07 23:07 UTC, ibdknox commented on _posts/2017-07-06-June.md
> +Thanks to everyone who came to our second meetup, in which we helped people install Eve and introduced the language to people who were new. We learned a lot by watching people go through the quicksta
there's no reason to say we don't have a plan, let's just... have a plan.

2017-07-08 00:27 UTC, ibdthor approved these changes

2017-07-08 00:28 UTC, ibdthor approved these changes

2017-07-08 00:28 UTC, ibdthor approved these changes

2017-07-08 00:29 UTC, ibdknox approved these changes

2017-07-08 00:32 UTC, joshuafcole approved these changes
:+1: :pizza: 📦

2017-07-08 00:34 UTC, merged